### PR TITLE
Parse YAML files by content (not by path name)

### PR DESCRIPTION
**Pull request by VSEphpbb**
Fix this issue: https://www.phpbb.com/customise/db/extension/mediaembed/support/topic/205021

### CODE REVIEW

**Comment by rxu** [comment]
Alternatively, ```Yaml::parseFile()``` could be used instead to parse yaml files by path.

**Comment by VSEphpbb** [comment]
Dont' see that in the Yaml class... But do see this:
```
    /**
     * Parses YAML into a PHP value.
     *
     * Usage:
     *
     *     $array = Yaml::parse(file_get_contents('config.yml'));
     *     print_r($array);
```

**Comment by rxu** [comment]
Ah, correct. It's in Symfony 4.0+.

**Comment by rxu** [comment]
BTW, does it make sense to use its code here?
https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/Yaml/Parser.php#L49-L66

**Comment by VSEphpbb** [comment]
No, not necessary

**Pull request merged**
