### PR TITLE
Add some more sites

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by VSEphpbb** [comment]
Mod D.B. is fine. It’s scraping. The URL has no useful data so the code which is numeric is being scraped from the page itself. That’s a good one because it’s an example of how to scrape a page to find the embed code ID.

**Comment by rxu** [comment]
It's not scraping for me for some reason. It's just shows plain URL in the post.

**Comment by rxu** [comment]
@JoshyPHP Is some particular PHP module needed for scraping to work?

**Comment by JoshyPHP** [comment]
No. ext/curl is used if available, otherwise it uses the default HTTP stream with file_get_contents()

Scraping often fails, much more often than one would expect. Some websites also reject requests based on geolocation and some sites force some users to solve a CAPTCHA to get a page, which will hinder scraping.

**Comment by rxu** [comment]
Well, I have no problems browsing Mod DB (no geolocation issues/no CAPTCHA etc.), so probably it's something else.

**Comment by rxu** [comment]
It's working now, thanks for the ```file_get_contents()``` hint.

**Comment by rxu** [comment]
```snotr``` is unavailable for me though.

**Comment by VSEphpbb** [comment]
@rxu anything else to add?

**Comment by rxu** [comment]
Nope, no other sites in mind for now.

**Comment by nonameviper** [comment]
redgifs

**Pull request merged**
