### PR TITLE
Prevent installation if old extension by s9e is present

### PR DESCRIPTION
**Pull request by VSEphpbb**

### CODE REVIEW

**Comment by VSEphpbb** [comment]
@rxu see if this helps when the old ext is still installed

**Comment by rxu** [comment]
It works but prevents enabling even if ```s9e/mediaembed``` ext is disabled/data deleted but files are still on server. That's kinda paranoiac but probably more reliable.

**Comment by VSEphpbb** [comment]
well the issue isn't so much if the old ext is installed, as it is there are two copies of the same library found, which caused the conflict you had.

**Comment by rxu** [comment]
Yeah, that force user to delete the old ext from server, which is fine. LGTM.

**Pull request merged**
